dist: xenial

sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t simtrack .

script:
  - docker run --rm simtrack /bin/bash -c "source /opt/ros/kinetic/setup.sh && catkin_make -DCMAKE_BUILD_TYPE=\"Release\""

